### ISSUE TITLE
Document basic installation and usage

### ISSUE THREAD

**Issue by andychisholm** [wikilinks/nel#1]

**Comment by geovedi** [comment]
can we have updated documentation on building a new model? information found on http://nel.readthedocs.org/en/latest/models/wikipedia/ and https://github.com/wikilinks/nel/blob/master/docs/models/wikipedia.md seems not reflecting the new changes.

**Comment by andychisholm** [comment]
Indeed, much has changed and i'm now working on updating the doco for a release with 0.3.

As a first step, I'll put together a bit of a guide for building models from scratch with Wikipedia.

**Comment by andychisholm** [comment]
readthedocs.org build fixed.

**Comment by andychisholm** [comment]
https://github.com/wikilinks/nel/blob/master/notebooks/train.ipynb
