### ISSUE TITLE
using any KB

### ISSUE THREAD

**Issue by vlordier** [wikilinks/nel#13]
In the doc, it says "link entity mentions to any knowledge base you like (not just Wikipedia and Freebase!)" 
=> any pointers/tutorials on how to use another kb / ontology ?

**Comment by andychisholm** [comment]
At a high level nel uses in-links to an entity page from the web to build disambiguation models. In this sense it's KB-agnostic, as long as you have references to the KB, you can build a disambiguation model for entities in that KB.

This works best for public-facing entity ontologies (wikipedia, imdb, twitter, nytimes/topics etc) where entities accrue lots of inbound links from the rest of the web.

[sift](https://github.com/wikilinks/sift) is the tool for actually turning big sets of linked documents into disambiguation models. Once you have a model for your target, you can use nel to do linking.

**Comment by iuria21** [comment]
Hi, first thanks for your repo and the docs. I want to use the library for the following case and want to know if you think it could work:
I have legal text with labeled references to laws and codes for these laws. I want to train the model to link the reference of the law with it's code.

I understand that I'll have to create a dataset like:
```
{"id": "doc1",
 "text": ".. as the Mortgage Law says ..."
"links" : [{"start":6 ,
             "stop":17,
             "target" "LW101"}]}
```

Thanks again!

**Comment by andychisholm** [comment]
That kind of use case sounds like a good fit to me. As long as you can massage a collection of text + links into that format, you should be able to build a custom linker.

**Comment by iuria21** [comment]
Thanks for the early answer, I'll try it!

**Comment by iuria21** [comment]
Hi, I have a question about the dataset. What should be the format of `docs`? y have the data to create it, but can't manage how should it be. I'm trying to download the wikipedia dump but I'm having problems so I can't check with the original notebook...
thanks
EDIT: I'm trying to write the data in a csv and load with pyspark, but I'm not getting the right format. I tried saving in three rows "_id" (string), "text"(string) and "links"(array of dicts). But it's no loading in the correct format. Please, I need help, I'm so stuck.

**EDIT: SOLVED**
