### ISSUE TITLE
Pre-trained

### ISSUE THREAD

**Issue by saurabhbh21** [wikilinks/nel#15]
Any pre-trained model available for Wikipedia dump? 
I'm unable to find the module to load model trained previously for getting entity linkage.

**Comment by andychisholm** [comment]
Not currently, though there's an existing issue covering this topic (#4) and [an example](https://github.com/wikilinks/nel/blob/master/notebooks/train.ipynb) available for building the models from public data.

**Comment by saurabhbh21** [comment]
I've trained a model a saved it, unable to load that model in classification time, can you help me which part of project deal with this?
