### ISSUE TITLE
More example

### ISSUE THREAD

**Issue by xindi-dumbledore** [wikilinks/nel#24]
Could you provide more examples on model building? For example, what are the codes you guys used to provide result in the paper? The current one in the ipynb is too simple and in general the codes are not readable (because they are lacking comments).

Thanks a lot!

**Comment by andychisholm** [comment]
The existing [example](https://github.com/wikilinks/nel/blob/master/notebooks/train.ipynb) shows the entire train + predict workflow, it doesn't need to be any more complicated than that!

To reproduce the paper results, you would add the full set of features from `nel.features` to featurisation by extending the featurisation pipeline:
```
feature_extraction = [
    EntityProbability('wikipedia'),
    NameProbability('wikipedia'),
    ...
]
```
