### ISSUE TITLE
Why the TrainLinearRanker is trained only over 100 documents?

### ISSUE THREAD

**Issue by iuria21** [wikilinks/nel#26]

**Comment by andychisholm** [comment]
Assuming you're talking about the [sample notebook](https://github.com/wikilinks/nel/blob/master/notebooks/train.ipynb)?

It's just a small example to show the full training workflow end-to-end, it's limited to 100 documents to run fast, but there's no limit.

**Comment by iuria21** [comment]
Thanks, that is just what I was thinking!
