### ISSUE TITLE
problem building Wikipedia Models

### ISSUE THREAD

**Issue by josefkr** [wikilinks/nel#6]
Hi,

I've been trying to run build-corpus but get an error about a missing file:

$ /mnt/big$ sift build-corpus --save redirects WikipediaRedirects latest-wikipedia/ json
17/02/23 09:36:44 WARN Utils: Your hostname, erwin resolves to a loopback address: 127.0.1.1; using 192.168.0.31 instead (on interface wlp3s0)
17/02/23 09:36:44 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
/mnt/big/ve/venv/bin/python: can't open file '/mnt/big/sift/__main__.py': [Errno 2] No such file or directory

This file "__main__.py" is specified at the end of the sift script but I can't find such a  file anywhere in a directory related to sift. 

$SPARK_HOME/bin/spark-submit \
    $SPARK_MASTER_SW \
    --driver-memory 16g \
    --executor-memory 16g \
    --conf spark.driver.maxResultSize=16g \
    sift/__main__.py \
    "$@"

Note also that I modified the sift script to use a newer spark version because the linked archive in the original sift script is no longer reachable:

http://d3kbcqa49mib13.cloudfront.net/spark-2.1.0-bin-hadoop2.7.tgz

Any help would be much appreciated.

**Comment by andychisholm** [comment]
Hi Josef, this is mainly a case of outdated doco in nel regarding sift.

A while ago, I ripped out the command line interface from sift in favor of a much simpler workflow using the API from a Jupyter notebooks. You can see an example building the wikipedia models using a notebook here: https://github.com/wikilinks/sift/blob/master/sift.ipynb

Right now, I'm actively working on a notebook to demonstrate building the sift models and training a nel linker directly from wikipedia dumps.


Here's what the first part of that notebook looks like right now:

```python
from sift.corpora import wikipedia, wikidata
from sift.models import text, links
wikipedia_base_path = '/data0/nel/data/wikipedia/dumps/20150901/'
wikipedia_corpus = wikipedia.WikipediaCorpus()(sc, wikipedia_base_path)

# preprocess the wikipedia corpus from wikimarkup
docs = wikipedia.WikipediaArticles()(wikipedia_corpus).cache()

wikipedia_pfx = 'en.wikipedia.org/wiki/'

# compute entity inlink counts
ec_model = links\
    .EntityCounts(min_count=5, filter_target=wikipedia_pfx)\
    .build(docs)\
    .map(links.EntityCounts.format_item)

# compute entity-anchor inlink counts
enc_model = links\
    .EntityNameCounts(lowercase=True, filter_target=wikipedia_pfx)\
    .build(docs)\
    .filter(lambda (name, counts): sum(counts.itervalues()) > 1)\
    .map(links.EntityNameCounts.format_item)

# store the computed models on disk in a file-based nel model store
# assume NEL_DATASTORE_URI=file:///data0/nel/
from nel.model.store.file import mmdict
mmdict.write('/data0/nel/models/necounts[wikipedia]', enc_model.repartition(8).map(lambda item: (item['_id'], item)).toLocalIterator())
mmdict.write('/data0/nel/models/ecounts[wikipedia]', ec_model.repartition(8).map(lambda item: (item['_id'], item)).toLocalIterator())
```

I'll be pushing the associated changes in the next day or so.

Also, thanks for the heads up on the dead spark link! I'll patch that now

**Comment by andychisholm** [comment]
CLI model building has been deprecated in 0.4 in favor of the python API.

See: [train.ipynb](https://github.com/wikilinks/nel/blob/master/notebooks/train.ipynb)
