### ISSUE TITLE
Add spacy tagger and update example notebook

### ISSUE THREAD

**Issue by josefkr** [wikilinks/nel#7]
Hi Andy,

the train notebook shows how to apply the model to a wikipedia doc froom which you've stripped the links. Could you also give a minimal example of how one can apply a trained model to a new (say, plain text) document? What preprocessing needs to happen?

Many thanks,
Josef

**Comment by andychisholm** [comment]
The linking pipeline operates over [nel.doc.Doc](https://github.com/wikilinks/nel/blob/master/nel/doc.py#L2) objects. All you need to create these is the plaintext of the document itself.

`
from nel.doc import Doc

d = Doc("The cat sat on the mat")
`

If the input text isn't plaintext, there are a few converters available in [nel.harness.format](https://github.com/wikilinks/nel/blob/master/nel/harness/format.py#L150) to convert documents in markdown / html to plaintext which might be helpful.

**Comment by josefkr** [comment]
Hi, unfortunately I have a followup question.

If I add the code below at the end of the code in your train-nontebook and run the cell, I get an empty document. Is there anything else that needs to be done with the new Doc object before putting it into linking_pipeline?

Many thanks,
Josef

--
ourdoc=linked_sample[0].text
mydoc=Doc(ourdoc)
mydoclinked = linking_pipeline(mydoc) 

display(Markdown(inject_markdown_links(mydoclinked.text, mydoclinked)))
---

**Comment by andychisholm** [comment]
Ah, yes - what's probably missing in that case is Mentions on the document. Sometimes you already have these, but if you don't, you'll need to add NER tagger to the linking pipeline. There's a few in nel already that plug into [existing taggers](https://github.com/wikilinks/nel/blob/master/nel/process/tag.py) (e.g. Stanford or SCHWA taggers). You can train a CRF from scratch.

I think the best option these days is for me to add a Spacy tagger. I'll prioritise adding that and updating the example to cover NER.

**Comment by andychisholm** [comment]
@josefkr I've added support for spacy NER and updated the training notebook with some sample output.

Note that you'll need to `pip install --upgrade -r requirements.txt` to grab the latest spacy version. Also checkout the spacy [release notes](https://github.com/explosion/spaCy/releases) for details on the available models. I would recommend the small/fast `en_core_web_sm` model.

E.g. to download/configure it:
```
python -m spacy download en_core_web_sm
python -m spacy link en_core_web_sm en_default
```

Hope that helps!
