### ISSUE TITLE
Training new model, Not enough space to cache rdd_6_7 in memory

### ISSUE THREAD

**Issue by Arminmsg** [wikilinks/nel#8]
Hi, I'm trying to train a german nel. I've downloaded the data, updated the `train.ipynb` to point to my data. Everything is working fine until I get to the commant `ec_model.take(1)`

For the first few minutes everything is running fine, no warnings but then I get the following warning
```
17/04/12 20:38:18 WARN MemoryStore: Not enough space to cache rdd_6_7 in memory! (computed 17.1 MB so far)
17/04/12 20:38:18 WARN BlockManager: Block rdd_6_7 could not be removed as it was not found on disk or in memory
17/04/12 20:38:18 WARN BlockManager: Putting block rdd_6_7 failed

```
and this goes on and on for rdd_6_8, rdd_6_9 and so on.

I'm running on Ubuntu 16.04 with 8gb ram, Spark 2.1, Python 2.7

How can I avoid this error?

**Comment by andychisholm** [comment]
This is an issue with the spark configuration. The defaults are quite conservative!

Try bumping `spark.driver.memory` to around 4g. You may also need to play with `spark.executor.memory`.

See: https://spark.apache.org/docs/latest/configuration.html#application-properties

**Comment by pganeshGapps** [comment]
Try following if using pyspark, it worked for me on aws EC2 instance.

`import pyspark as pyspark

sc.stop()

conf = pyspark.SparkConf().setAll([('spark.executor.memory', '16g'),('spark.driver.memory','16g')])

sc = pyspark.SparkContext(conf=conf)`

If spark still throws same error, try to tweak (increase) with 'spark.executor.memory' or 'spark.driver.memory'.
